package coolThings;

public class LoveAnimation {
    public static void main(String[] args) throws InterruptedException {
        String[] loveMessages = {
            "I love you (English)",
            "Te amo (Spanish)",
            "Je t'aime (French)",
            "Ich liebe dich (German)",
            "Ti amo (Italian)",
            "Eu te amo (Portuguese)",
            "S'agapo (Greek)",
            "Ya tebya lyublyu (Russian)",
            "Aishiteru (Japanese)",
            "Saranghae (Korean)",
            "Wo ai ni (Mandarin Chinese)",
            "Ngiyakuthanda (Zulu)",
            "Ek het jou lief (Afrikaans)",
            "Ami tomake bhalobashi (Bengali)",
            "Main tumse pyaar karta hoon (Hindi)",
            "Ana behibek (Arabic - male to female)",
            "Taim i' ngra leat (Irish)",
            "Aroha ahau ki a koe (Maori)",
            "Kuv hlub koj (Hmong)",
            "Ndagukunda (Kinyarwanda)",
            "Nakupenda (Swahili)",
            "Mahal kita (Tagalog)",
            "Saya cinta padamu (Malay/Indonesian)",
            "T'estimo (Catalan)",
            "Volim te (Serbian/Croatian/Bosnian)",
            "Ljubim te (Slovenian)",
            "Jeg elsker dig (Danish)",
            "Jeg elsker deg (Norwegian)",
            "Jag älskar dig (Swedish)",
            "Kocham cię (Polish)",
            "Milujem ťa (Slovak)",
            "Szeretlek (Hungarian)",
            "Te iubesc (Romanian)",
            "Ich lieb Di (Swiss German)",
            "Ya lyublyu tebya (Ukrainian)",
            "Ch'terème (Picard)",
            "Mi amas vin (Esperanto)",
            "Eg elski teg (Faroese)",
            "Inhobok (Maltese)",
            "Tha gaol agam ort (Scottish Gaelic)",
            "Ani ohev otach (Hebrew - male to female)",
            "Ani ohevet otcha (Hebrew - female to male)",
            "Mo ni fe re (Yoruba)",
            "Mi ta stimabo (Papiamento)",
            "Ke a go rata (Setswana)",
            "Taim i’ ngra leat (Irish Gaelic)",
            "Aloha wau ia ‘oe (Hawaiian)",
            "Phom rak khun (Thai - male to female)",
            "Chan rak khun (Thai - female to male)",
            "Bahibak (Levantine Arabic)",
            "Uhibbuka (Formal Arabic - male to female)",
            "Ninapenda wewe (Swahili)",
            "Hum tumhe pyaar karte hain (Hindi plural)",
            "Me do wo (Twi - Ghana)",
            "Mi lob yu (Tok Pisin)",
            "Mo te iubesc (Moldovan)",
            "Ich lieb dich (Casual German)",
            "Ti voglio bene (Friendly Italian)",
            "Obicham te (Bulgarian)",
            "Rwy’n dy garu di (Welsh)",
            "Ya tabe kahayu (Belarusian)",
            "Is breá liom tú (Irish)",
            "Minä rakastan sinua (Finnish)",
            "Eg elskar deg (Norwegian Nynorsk)",
            "Me rakastan sinua (Finnish informal)",
            "Ana uhibbuka (Arabic male to male)",
            "Ana uhibbuki (Arabic male to female)",
            "Mena ohevet otach (Hebrew female to female)",
            "Ego amo te (Latin)",
            "Tave myliu (Lithuanian)",
            "Ma armastan sind (Estonian)",
            "Volim te puno (Serbian)",
            "Mi amas vin tre (Esperanto)",
            "Te dua (Albanian)",
            "Man to ra doost daram (Persian/Farsi)",
            "Aš tave myliu (Lithuanian)",
            "Mən səni sevirəm (Azerbaijani)",
            "Seni seviyorum (Turkish)",
            "Seviyorum seni (Turkish casual)",
            "Ben seni seviyorum (Turkish formal)",
            "Ti si mi život (Bosnian)",
            "Te sakam (Macedonian)",
            "T'estim molt (Catalan informal)",
            "Sh’t do (Albanian Gheg)",
            "Ngikuthanda (Zulu variant)",
            "Ke rata wena (Sesotho)",
            "Mahal na mahal kita (Filipino intensified)",
            "Aku cinta padamu (Malay formal)",
            "Aku sayang kamu (Malay casual)",
            "Aku tresno awakmu (Javanese)",
            "Kami ay nagmamahal sa iyo (Tagalog plural)",
            "Saya sayang kamu (Indonesian casual)",
            "Seni çok seviyorum (Turkish strong)",
            "Bim alef ohevet otcha (Hebrew informal)"
        };

        while (true) { // Infinite loop to keep animating
            for (String msg : loveMessages) {
                System.out.print("\r" + msg + "   "); // \r brings cursor to start
                Thread.sleep(500); // half-second delay
            }
        }
    }
}

